/*
    SpeedReaderJS - Library for speed reading
    License - https://github.com/kadymov/SpeedReaderJS/LICENSE.md
    Copyright (c) 2014 Aleksandr Kadymov (www.kadymov.pw)
*/

(function(l,p){function B(h){h&&(C?(h(),u=!0):l.addEventListener("DOMContentLoaded",function(){h();u=!0},!1))}var r=function(){function h(){var g=JSON.stringify(t);l.sessionStorage.setItem(p,g)}var p="speedReader",t={formTop:0,formLeft:0,dockingBottom:!1,dockingRight:!1,formWidth:260};return{getOption:function(g){var f=l.sessionStorage.getItem(p);f?t=JSON.parse(f):h();return t[g]},setOption:function(g,f){if("[object Object]"===Object.prototype.toString.call(g))for(var c in g)g.hasOwnProperty(c)&&
(t[c]=g[c]);else t[g]=f;h()}}}(),v=function(){function h(){var d=g,a=m-g,b=s/2+10,e=n/2,q=e-b,b=e+b,e=(m-2*g)/3;c.save();c.clearRect(0,0,m,n);c.lineWidth=2;c.beginPath();c.moveTo(d,q);c.lineTo(a,q);c.stroke();c.beginPath();c.moveTo(d,b);c.lineTo(a,b);c.stroke();c.beginPath();c.moveTo(e,q);c.lineTo(e,b);c.stroke();l()}function l(){var d=n/2,a=s/2+10,b=d-a;c.clearRect(0,b+5,m,d+a-b-10)}function p(d){if(d){k=d;var a=d.length,b=1==a?0:6>a?1:10>a?2:14>a?3:4,a=n/2,e=(m-2*g)/3;l();c.save();c.font=s+"px Arial";
c.textBaseline="middle";var q=d.charAt(b),y=c.measureText(q).width,e=e-y/2,h=d.substring(0,b),f=e-c.measureText(h).width;d=d.substring(b+1);y=e+y;c.fillText(h,f,a);c.fillText(d,y,a);c.fillStyle="red";c.fillText(q,e,a);c.restore()}}var g=10,f=null,c=null,m=0,n=0,s=0,k="";return{init:function(d){f=d;d=document.defaultView.getComputedStyle(d);m=parseInt(d.width,10);n=0.2*m;f.style.height=n+"px";f.width=m;f.height=n;c=f.getContext("2d");s=m/15;h()},resize:function(c){m=c;n=0.2*c;f.style.height=n+"px";
f.width=m;f.height=n;s=m/15;h();p(k)},drawText:p}}(),k=function(){function h(){if(s){var a=g[f++];if(a===p)s=!1,f=0,r&&r();else{var b;a:switch(a.charAt(a.length-1)){case ",":case ";":b=n*l;break a;case ".":case "?":case "!":b=n*k;break a;default:b=n}m.drawText(a);d&&d(f,c);setTimeout(function(){h()},b)}}}var l=1.9,k=2.4,g=null,f=0,c=0,m=null,n=240,s=!1,r=null,d=null;return{init:function(a,b,e){m=a;r=b;d=e},loadText:function(a){this.stop();g=a.split(/[\s\r\n\t]/);c=g.length},play:function(){!s&&g&&
g.length&&(s=!0,h())},pause:function(){s=!1},stop:function(){s=!1;f=0},back:function(){if(g&&g.length){this.pause();f-=10;0>f&&(f=0);m.drawText(g[f++]);var a=this;setTimeout(function(){a.play()},1E3)}},setSpeed:function(a){n=6E4/a},isPlay:function(){return s},getWordId:function(){return f},setWordId:function(a){if(!g||!g.length)return!1;f=a;m.drawText(g[a]);return!0},getWordsCount:function(){return c}}}(),w=function(){function h(a,b,e,q){a=document.createElement(a);b!==p&&(a.className=b);e!==p&&(a.innerHTML=
e);q!==p&&a.setAttribute("title",q);return a}function u(a,b,e,q,c){function h(b){document.body.classList.add("selection-off");var q=document.defaultView.getComputedStyle(a),c=document.documentElement;z=parseInt(q.left,10);m=parseInt(q.top,10);g=b.clientX;l=b.clientY;c.addEventListener("mousemove",d,!1);c.addEventListener("mouseup",f,!1);e!==p&&e.call(a,k)}function d(b){k.left=z+b.clientX-g;k.top=m+b.clientY-l;q!==p&&q.call(a,k);a.style.left=k.left+"px";a.style.top=k.top+"px"}function f(){document.body.classList.remove("selection-off");
var b=document.documentElement;b.removeEventListener("mousemove",d,!1);b.removeEventListener("mouseup",h,!1);c!==p&&c.call(a,k)}var g=0,l=0,z=0,m=0,n=document.defaultView.getComputedStyle(a),k={left:n.left,top:n.top};b.addEventListener("mousedown",h,!1)}function t(a,b,e,q){function c(b){b=f+b.clientX-g;b=b<d?d:b>l.innerWidth-30?l.innerWidth-30:b;a.style.width=b+"px";k=b;e!==p&&e(b)}function h(){document.body.classList.remove("selection-off");document.documentElement.removeEventListener("mousemove",
c,!1);document.documentElement.removeEventListener("mouseup",h,!1);q!==p&&q(k)}var d=260,g=0,f=0,k=0;b.addEventListener("mousedown",function(b){document.body.classList.add("selection-off");var e=document.defaultView.getComputedStyle(a);g=b.clientX;f=parseInt(e.width,10);parseInt(e.height,10);document.documentElement.addEventListener("mouseup",h,!1);document.documentElement.addEventListener("mousemove",c,!1)},!1)}function g(a){var b=a,e=h("div","speed-reader-pbar",p,"Progress"),c=h("div","speed-reader-prun"),
d=0,g=document.documentElement,f=function(a){a=a.pageX-e.getBoundingClientRect().left;var b=parseInt(document.defaultView.getComputedStyle(e).width,10);d=parseInt(a/(b/100),10);c.style.width=d+"%"},l=function(a){f(a);b&&b(d)},k=function(){document.body.classList.remove("selection-off");g.removeEventListener("mousemove",l,!1);g.removeEventListener("mouseup",k,!1)};e.appendChild(c);e.addEventListener("mousedown",function(a){document.body.classList.add("selection-off");f(a);g.addEventListener("mousemove",
l,!1);g.addEventListener("mouseup",k,!1);b&&b(d)},!1);return{val:function(a){if(a===p)return d;d=a;c.style.width=d+"%"},setListener:function(a){b=a},getElem:function(){return e}}}function f(){function a(e){27===e.which&&(b.classList.remove("full-scr"),document.body.classList.remove("scroll-off"),e=document.defaultView.getComputedStyle(b),v.resize(parseInt(e.width,10),parseInt(e.height,10)),l.removeEventListener("keydown",a,!1))}var b=h("div","speed-reader"),e=h("div","speed-reader-caption",s),c=h("div",
"speed-reader-infbut",p,"Information"),d=h("div","speed-reader-fullbut",p,"Full screen mode"),f=h("ul","speed-reader-panel"),k=h("li","speed-reader-button play","&nbsp;","Play/Pause"),m=h("li","speed-reader-button stop","&nbsp;","Stop"),n=h("li","speed-reader-button back","&nbsp;","Back"),r=h("li",p,"Speed: "),t="<option>"+x.join(" pws</option><option>")+" pws</option>",t=h("select","speed-reader-spdsel",t),u=h("div","speed-reader-resizer"),w=h("canvas","speed-reader-canv"),A=new g;e.appendChild(d);
e.appendChild(c);r.appendChild(t);f.appendChild(k);f.appendChild(m);f.appendChild(n);f.appendChild(r);b.appendChild(e);b.appendChild(w);b.appendChild(A.getElem());b.appendChild(f);b.appendChild(u);d.addEventListener("click",function(){b.classList.toggle("full-scr");document.body.classList.toggle("scroll-off");var e=document.defaultView.getComputedStyle(b);v.resize(parseInt(e.width,10),parseInt(e.height,10));l.addEventListener("keydown",a,!1)});c.addEventListener("click",function(){var a=l.open("",
"Information","width=300,height=220,left="+(l.innerWidth-300)/2+",top="+(l.innerHeight-220)/2+"menubar=no,toolbar=no,location=no,directories=no,status=false,resizable=no, scrollbars=yes");a.document.body.innerHTML='<style>body {font: 14px/14px Arial; padding: 5px; text-align:center;background:#eee}a{background: #ddd; padding: 3px; border-radius:3px;}</style><h1>SpeedReader.JS</h1><p>Author: Alexandr Kadymov</p><p><a href="http://kadymov.pw" target="_blank">www.kadymov.pw</a></p><p><a href="https://github.com/kadymov/SpeedReaderJS" target="_blank">GitHub Repo</a></p><h2>Instructions</h2>1) Select text<br/>2) Press play';
a.focus()});return{form:b,capt:e,play:k,stop:m,back:n,full:d,spd:t,resize:u,canv:w,pbar:A}}function c(a){var b=r.getOption("formLeft"),e=r.getOption("formTop"),c=parseInt(document.defaultView.getComputedStyle(a).width,10),d=r.getOption("formWidth");v.resize(c===l.innerWidth?c:d);r.getOption("dockingRight")&&(b=l.innerWidth-d);r.getOption("dockingBottom")&&(e=document.defaultView.getComputedStyle(a),e=l.innerHeight-parseInt(e.height,10));a.style.width=d;a.style.left=b+"px";a.style.top=e+"px";r.setOption({formLeft:b,
formTop:e})}function m(a){var b="";v.init(a.canv);k.init(v,function(){a.play.classList.remove("pause")},function(b,c){var d=parseInt(b/(c/100),10);a.pbar.val(d)});a.play.addEventListener("click",function(a){if(k.isPlay())k.pause(),a.target.classList.remove("pause");else{var c=l.getSelection().toString();c.length&&b!==c&&(k.loadText(c),b=c);b.length&&(k.play(),a.target.classList.add("pause"))}},!1);a.stop.addEventListener("click",function(){k.stop();a.pbar.val(0);a.play.classList.remove("pause")},
!1);a.back.addEventListener("click",function(){k.back()},!1);a.spd.addEventListener("change",function(a){a=parseInt(a.target.value,10);k.setSpeed(a)});a.pbar.setListener(function(a){var b=k.getWordsCount();a=parseInt(b/100*a,10);k.setWordId(a)})}function n(){var a=f(),b=!1,d=!1;u(a.form,a.capt,p,function(a){var c=a.left,f=a.top,g=document.defaultView.getComputedStyle(this),h=parseInt(g.width,10),g=parseInt(g.height,10),k=l.innerWidth,m=l.innerHeight;d=b=!1;20>f&&(f=0);f+g>m-20&&(f=m-g,b=!0);20>c&&
(c=0);c+h>k-20&&(c=k-h,d=!0);a.left=c;a.top=f},function(a){r.setOption({formLeft:a.left,formTop:a.top,dockingBottom:b,dockingRight:d})});t(a.form,a.resize,function(a){v.resize(a)},function(a){r.setOption("formWidth",a)});m(a);document.body.appendChild(a.form);c(a.form);l.addEventListener("resize",function(){c(a.form)},!1);return a}var s="SpeedReader.JS",x=[250,300,350,400,450,500,550,600,650,700,750,800,850,900,950,1E3],d=null;return{show:function(){d||(d=n());d.form.style.diplay="block"},hide:function(){d&&
d.form&&(d.form.style.diplay="none")}}}(),C=!1,u=!1,D=l.srjs,x={show:function(){B(w.show)},hide:function(){u&&(k.stop(),w.hide())},noConflict:function(){l.srjs===x&&(l.srjs=D);return x}};l.srjs=x})(window);